# Generated by Django 4.2.16 on 2024-10-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='home_address',
            new_name='billing_address',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
