# Generated by Django 4.2.16 on 2024-10-09 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_rename_home_address_userinfo_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='shipping_address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping'), ('home', 'Home'), ('office', 'Office')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
