# Generated by Django 4.2.16 on 2024-10-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_userinfo_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
